#!/usr/bin/env python3
"""QQ chat history parser

Supported formats:
- txt format exported by QQ Message Manager
- mht format exported by QQ Message Manager

Usage:
    python3 qq_parser.py --file <path> --target <name> --output <output_path>
    """

    import argparse
    import re
    import os
    import sys
    from pathlib import Path


    def parse_qq_txt(file_path: str, target_name: str) -> dict:
        """Parse QQ exported txt format
            
                Typical format:
                    Message history (this message history is in text format, does not include images or other media)
                        
                            Message group: My friends
                                ================================================================
                                    Message target: Zhang San
                                        ================================================================
                                            
                                                2024-01-15 20:30:45 Zhang San(123456)
                                                    So tired today
                                                        
                                                            2024-01-15 20:31:02 Me(654321)
                                                                What's wrong
                                                                    """
                                                                        messages = []
                                                                            current_msg = None
                                                                                
                                                                                    # QQ timestamp + sender pattern
                                                                                        msg_pattern = re.compile(r'^(\d{4}-\d{2}-\d{2}\s+\d{2}:\d{2}:\d{2})\s+(.+?)(?:\((\d+)\))?\s*$')
                                                                                            
                                                                                                with open(file_path, 'r', encoding='utf-8', errors='ignore') as f:
                                                                                                        for line in f:
                                                                                                                    line = line.rstrip('\n')
                                                                                                                                match = msg_pattern.match(line)
                                                                                                                                            if match:
                                                                                                                                                            if current_msg:
                                                                                                                                                                                messages.append(current_msg)
                                                                                                                                                                                                current_msg = {
                                                                                                                                                                                                                    'timestamp': match.group(1),
                                                                                                                                                                                                                                        'sender': match.group(2),
                                                                                                                                                                                                                                                            'qq_id': match.group(3),
                                                                                                                                                                                                                                                                                'content': '',
                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                            elif current_msg is not None and line.strip():
                                                                                                                                                                                                                                                                                                                            current_msg['content'] += line + '\n'
                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                    if current_msg:
                                                                                                                                                                                                                                                                                                                                            messages.append(current_msg)
                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                    for m in messages:
                                                                                                                                                                                                                                                                                                                                                            m['content'] = m['content'].strip()
                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                    target_msgs = [m for m in messages if target_name in m['sender']]
                                                                                                                                                                                                                                                                                                                                                                        all_target_text = '\n'.join([m['content'] for m in target_msgs])
                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                return {
                                                                                                                                                                                                                                                                                                                                                                                        'messages': messages,
                                                                                                                                                                                                                                                                                                                                                                                                'target_name': target_name,
                                                                                                                                                                                                                                                                                                                                                                                                        'format': 'qq_txt',
                                                                                                                                                                                                                                                                                                                                                                                                                'total_messages': len(messages),
                                                                                                                                                                                                                                                                                                                                                                                                                        'target_messages': len(target_msgs),
                                                                                                                                                                                                                                                                                                                                                                                                                                'user_messages': len(messages) - len(target_msgs),
                                                                                                                                                                                                                                                                                                                                                                                                                                        'sample_messages': [m['content'] for m in target_msgs[:50] if m.get('content')],
                                                                                                                                                                                                                                                                                                                                                                                                                                                'raw_text': all_target_text[:10000],
                                                                                                                                                                                                                                                                                                                                                                                                                                                    }


                                                                                                                                                                                                                                                                                                                                                                                                                                                    def parse_qq_mht(file_path: str, target_name: str) -> dict:
                                                                                                                                                                                                                                                                                                                                                                                                                                                        """Parse QQ exported mht format (HTML content)"""
                                                                                                                                                                                                                                                                                                                                                                                                                                                            with open(file_path, 'r', encoding='utf-8', errors='ignore') as f:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    content = f.read()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            # Remove HTML tags
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                clean_text = re.sub(r'<[^>]+>', '\n', content)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    clean_text = re.sub(r'\n{3,}', '\n\n', clean_text)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'target_name': target_name,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'format': 'mht',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'raw_text': clean_text[:20000],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'note': 'MHT format, plain text extracted'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                def main():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    parser = argparse.ArgumentParser(description='QQ chat history parser')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        parser.add_argument('--file', required=True, help='Input file path')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            parser.add_argument('--target', required=True, help="Ex's name/nickname")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                parser.add_argument('--output', required=True, help='Output file path')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        args = parser.parse_args()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if not os.path.exists(args.file):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        print(f"Error: file not found {args.file}", file=sys.stderr)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                sys.exit(1)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ext = Path(args.file).suffix.lower()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if ext == '.mht' or ext == '.mhtml':
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    result = parse_qq_mht(args.file, args.target)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                result = parse_qq_txt(args.file, args.target)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        os.makedirs(os.path.dirname(args.output) or '.', exist_ok=True)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            with open(args.output, 'w', encoding='utf-8') as f:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    f.write(f"# QQ Chat History Analysis — {args.target}\n\n")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            f.write(f"Total messages: {result.get('total_messages', 'N/A')}\n")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    f.write(f"Their messages: {result.get('target_messages', 'N/A')}\n\n")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if result.get('sample_messages'):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                f.write("## Message Samples\n")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            for i, msg in enumerate(result['sample_messages'], 1):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            f.write(f"{i}. {msg}\n")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    elif result.get('raw_text'):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                f.write("## Raw Text (excerpt)\n\n")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            f.write(result['raw_text'][:10000])
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print(f"Analysis complete, results written to {args.output}")


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if __name__ == '__main__':
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        main()