#!/usr/bin/env python3
"""Skill file manager

Manages file operations for ex Skills: list, create directories, generate combined SKILL.md.

Usage:
    python3 skill_writer.py --action <list|init|combine> --base-dir <path> [--slug <slug>]
    """

    import argparse
    import os
    import sys
    import json
    from pathlib import Path
    from datetime import datetime


    def list_skills(base_dir: str):
        """List all generated ex Skills"""
            if not os.path.isdir(base_dir):
                    print("No ex Skills have been created yet.")
                            return
                                
                                    skills = []
                                        for slug in sorted(os.listdir(base_dir)):
                                                meta_path = os.path.join(base_dir, slug, 'meta.json')
                                                        if os.path.exists(meta_path):
                                                                    with open(meta_path, 'r', encoding='utf-8') as f:
                                                                                    meta = json.load(f)
                                                                                                skills.append({
                                                                                                                'slug': slug,
                                                                                                                                'name': meta.get('name', slug),
                                                                                                                                                'version': meta.get('version', '?'),
                                                                                                                                                                'updated_at': meta.get('updated_at', '?'),
                                                                                                                                                                                'profile': meta.get('profile', {}),
                                                                                                                                                                                            })
                                                                                                                                                                                                
                                                                                                                                                                                                    if not skills:
                                                                                                                                                                                                            print("No ex Skills found.")
                                                                                                                                                                                                                    return
                                                                                                                                                                                                                        
                                                                                                                                                                                                                            print("Your ex Skills:")
                                                                                                                                                                                                                                for s in skills:
                                                                                                                                                                                                                                        profile = s.get('profile', {})
                                                                                                                                                                                                                                                profile_str = ''
                                                                                                                                                                                                                                                        if profile.get('occupation'):
                                                                                                                                                                                                                                                                    profile_str += f" · {profile['occupation']}"
                                                                                                                                                                                                                                                                            if profile.get('together_duration'):
                                                                                                                                                                                                                                                                                        profile_str += f" · together {profile['together_duration']}"
                                                                                                                                                                                                                                                                                                print(f"  • {s['slug']} ({s['name']}{profile_str})")
                                                                                                                                                                                                                                                                                                        print(f"    version {s['version']}, last updated {s['updated_at']}")
                                                                                                                                                                                                                                                                                                                print()


                                                                                                                                                                                                                                                                                                                def init_skill(base_dir: str, slug: str):
                                                                                                                                                                                                                                                                                                                    """Initialize Skill directory structure"""
                                                                                                                                                                                                                                                                                                                        skill_dir = os.path.join(base_dir, slug)
                                                                                                                                                                                                                                                                                                                            dirs = [
                                                                                                                                                                                                                                                                                                                                    os.path.join(skill_dir, 'versions'),
                                                                                                                                                                                                                                                                                                                                            os.path.join(skill_dir, 'memories', 'chats'),
                                                                                                                                                                                                                                                                                                                                                    os.path.join(skill_dir, 'memories', 'photos'),
                                                                                                                                                                                                                                                                                                                                                            os.path.join(skill_dir, 'memories', 'social'),
                                                                                                                                                                                                                                                                                                                                                                ]
                                                                                                                                                                                                                                                                                                                                                                    for d in dirs:
                                                                                                                                                                                                                                                                                                                                                                            os.makedirs(d, exist_ok=True)
                                                                                                                                                                                                                                                                                                                                                                                print(f"Initialized directory: {skill_dir}")


                                                                                                                                                                                                                                                                                                                                                                                def combine_skill(base_dir: str, slug: str):
                                                                                                                                                                                                                                                                                                                                                                                    """Combine memory.md + persona.md to generate complete SKILL.md"""
                                                                                                                                                                                                                                                                                                                                                                                        skill_dir = os.path.join(base_dir, slug)
                                                                                                                                                                                                                                                                                                                                                                                            meta_path = os.path.join(skill_dir, 'meta.json')
                                                                                                                                                                                                                                                                                                                                                                                                memory_path = os.path.join(skill_dir, 'memory.md')
                                                                                                                                                                                                                                                                                                                                                                                                    persona_path = os.path.join(skill_dir, 'persona.md')
                                                                                                                                                                                                                                                                                                                                                                                                        skill_path = os.path.join(skill_dir, 'SKILL.md')
                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                if not os.path.exists(meta_path):
                                                                                                                                                                                                                                                                                                                                                                                                                        print(f"Error: meta.json not found at {meta_path}", file=sys.stderr)
                                                                                                                                                                                                                                                                                                                                                                                                                                sys.exit(1)
                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                        with open(meta_path, 'r', encoding='utf-8') as f:
                                                                                                                                                                                                                                                                                                                                                                                                                                                meta = json.load(f)
                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                        name = meta.get('name', slug)
                                                                                                                                                                                                                                                                                                                                                                                                                                                            profile = meta.get('profile', {})
                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    memory_content = ''
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if os.path.exists(memory_path):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                with open(memory_path, 'r', encoding='utf-8') as f:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            memory_content = f.read()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    persona_content = ''
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if os.path.exists(persona_path):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                with open(persona_path, 'r', encoding='utf-8') as f:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            persona_content = f.read()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    desc_parts = []
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if profile.get('occupation'):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                desc_parts.append(profile['occupation'])
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if profile.get('mbti'):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            desc_parts.append(profile['mbti'])
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if profile.get('zodiac'):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        desc_parts.append(profile['zodiac'])
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            description = f"{name}, {', '.join(desc_parts)}" if desc_parts else name
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    skill_md = f"""---
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    name: ex-{slug}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    description: {description}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    user-invocable: true
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ---

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # {name}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {description}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ---

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ## PART A: Relationship Memory

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {memory_content}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ---

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ## PART B: Persona

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {persona_content}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ---

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ## Operating Rules

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    1. You are {name}, not an AI assistant. Speak in their way, think with their logic
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    2. First use PART B to determine: how would they respond to this topic? What attitude?
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    3. Then PART A supplements: combine shared memories to make the response more authentic
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    4. Always maintain PART B's expression style, including catchphrases, filler words, punctuation habits
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    5. Layer 0 hard rules take highest priority:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       - Never say what they'd never say in real life
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          - Don't suddenly become perfect or unconditionally accepting (unless they were always like that)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             - Keep their "edges" — these imperfections are what make them real
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                - If asked "do you love me" type questions, answer in the way THEY would, not what the user wants to hear
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                """
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        with open(skill_path, 'w', encoding='utf-8') as f:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                f.write(skill_md)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        print(f"Generated {skill_path}")


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        def main():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            parser = argparse.ArgumentParser(description='Skill file manager')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                parser.add_argument('--action', required=True, choices=['list', 'init', 'combine'], help='Action to perform')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    parser.add_argument('--base-dir', default='./exes', help='Base directory for ex Skills')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        parser.add_argument('--slug', help='Ex identifier/codename')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                args = parser.parse_args()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if args.action == 'list':
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                list_skills(args.base_dir)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    elif args.action == 'init':
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if not args.slug:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        print("Error: init requires --slug argument", file=sys.stderr)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    sys.exit(1)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            init_skill(args.base_dir, args.slug)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                elif args.action == 'combine':
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if not args.slug:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print("Error: combine requires --slug argument", file=sys.stderr)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                sys.exit(1)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        combine_skill(args.base_dir, args.slug)


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if __name__ == '__main__':
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            main()