#!/usr/bin/env python3
"""Social media content parser

Parses WeChat Moments, Weibo, Xiaohongshu, Instagram and other social media screenshots or export files.
Screenshots are read directly through Claude's Read tool (supports images); this tool handles text exports.

Usage:
    python3 social_parser.py --dir <screenshot_dir> --output <output_path>
    """

    import argparse
    import os
    import sys
    from pathlib import Path


    def scan_directory(dir_path: str) -> dict:
        """Scan directory, classify files by type"""
            files = {'images': [], 'texts': [], 'other': []}
                
                    image_exts = {'.jpg', '.jpeg', '.png', '.gif', '.webp', '.bmp'}
                        text_exts = {'.txt', '.md', '.json', '.csv'}
                            
                                for root, dirs, filenames in os.walk(dir_path):
                                        for fname in filenames:
                                                    fpath = os.path.join(root, fname)
                                                                ext = Path(fname).suffix.lower()
                                                                            if ext in image_exts:
                                                                                            files['images'].append(fpath)
                                                                                                        elif ext in text_exts:
                                                                                                                        files['texts'].append(fpath)
                                                                                                                                    else:
                                                                                                                                                    files['other'].append(fpath)
                                                                                                                                                        
                                                                                                                                                            return files


                                                                                                                                                            def main():
                                                                                                                                                                parser = argparse.ArgumentParser(description='Social media content parser')
                                                                                                                                                                    parser.add_argument('--dir', required=True, help='Screenshot or export directory path')
                                                                                                                                                                        parser.add_argument('--output', required=True, help='Output file path')
                                                                                                                                                                            
                                                                                                                                                                                args = parser.parse_args()
                                                                                                                                                                                    
                                                                                                                                                                                        if not os.path.exists(args.dir):
                                                                                                                                                                                                print(f"Error: directory not found {args.dir}", file=sys.stderr)
                                                                                                                                                                                                        sys.exit(1)
                                                                                                                                                                                                            
                                                                                                                                                                                                                files = scan_directory(args.dir)
                                                                                                                                                                                                                    
                                                                                                                                                                                                                        os.makedirs(os.path.dirname(args.output) or '.', exist_ok=True)
                                                                                                                                                                                                                            with open(args.output, 'w', encoding='utf-8') as f:
                                                                                                                                                                                                                                    f.write(f"# Social Media Content Scan\n\n")
                                                                                                                                                                                                                                            f.write(f"Scanned directory: {args.dir}\n\n")
                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                            f.write(f"## File Statistics\n")
                                                                                                                                                                                                                                                                    f.write(f"- Image files: {len(files['images'])}\n")
                                                                                                                                                                                                                                                                            f.write(f"- Text files: {len(files['texts'])}\n")
                                                                                                                                                                                                                                                                                    f.write(f"- Other files: {len(files['other'])}\n\n")
                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                    if files['images']:
                                                                                                                                                                                                                                                                                                                f.write("## Image List (use Read tool to view each one)\n")
                                                                                                                                                                                                                                                                                                                            for img in sorted(files['images']):
                                                                                                                                                                                                                                                                                                                                            f.write(f"- {img}\n")
                                                                                                                                                                                                                                                                                                                                                        f.write("\n")
                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                        if files['texts']:
                                                                                                                                                                                                                                                                                                                                                                                    f.write("## Text Content\n")
                                                                                                                                                                                                                                                                                                                                                                                                for txt in sorted(files['texts']):
                                                                                                                                                                                                                                                                                                                                                                                                                f.write(f"\n### {os.path.basename(txt)}\n")
                                                                                                                                                                                                                                                                                                                                                                                                                                try:
                                                                                                                                                                                                                                                                                                                                                                                                                                                    with open(txt, 'r', encoding='utf-8', errors='ignore') as tf:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            content = tf.read(5000)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                f.write(f"```\n{content}\n```\n")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                except Exception as e:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    f.write(f"Failed to read: {e}\n")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print(f"Scan complete, results written to {args.output}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                print(f"Note: Image screenshots need to be viewed with the Read tool; this tool only lists file paths")


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if __name__ == '__main__':
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    main()