#!/usr/bin/env python3
"""Version archive and rollback manager

Usage:
    python3 version_manager.py --action <backup|rollback|list> --slug <slug> --base-dir <path> [--version <v>]
    """

    import argparse
    import os
    import sys
    import shutil
    import json
    from datetime import datetime


    def backup(base_dir: str, slug: str):
        """Back up current version"""
            skill_dir = os.path.join(base_dir, slug)
                versions_dir = os.path.join(skill_dir, 'versions')
                    meta_path = os.path.join(skill_dir, 'meta.json')
                        
                            if not os.path.exists(meta_path):
                                    print(f"Error: meta.json not found", file=sys.stderr)
                                            sys.exit(1)
                                                
                                                    with open(meta_path, 'r', encoding='utf-8') as f:
                                                            meta = json.load(f)
                                                                
                                                                    current_version = meta.get('version', 'v0')
                                                                        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
                                                                            backup_name = f"{current_version}_{timestamp}"
                                                                                backup_dir = os.path.join(versions_dir, backup_name)
                                                                                    
                                                                                        os.makedirs(backup_dir, exist_ok=True)
                                                                                            
                                                                                                # Back up core files
                                                                                                    for fname in ['memory.md', 'persona.md', 'SKILL.md', 'meta.json']:
                                                                                                            src = os.path.join(skill_dir, fname)
                                                                                                                    if os.path.exists(src):
                                                                                                                                shutil.copy2(src, os.path.join(backup_dir, fname))
                                                                                                                                    
                                                                                                                                        print(f"Backed up to version {backup_name}")


                                                                                                                                        def rollback(base_dir: str, slug: str, version: str):
                                                                                                                                            """Roll back to a historical version"""
                                                                                                                                                skill_dir = os.path.join(base_dir, slug)
                                                                                                                                                    versions_dir = os.path.join(skill_dir, 'versions')
                                                                                                                                                        
                                                                                                                                                            # Find target version directory
                                                                                                                                                                target_dir = None
                                                                                                                                                                    for vname in sorted(os.listdir(versions_dir), reverse=True):
                                                                                                                                                                            if vname.startswith(version) or vname == version:
                                                                                                                                                                                        target_dir = os.path.join(versions_dir, vname)
                                                                                                                                                                                                    break
                                                                                                                                                                                                        
                                                                                                                                                                                                            if not target_dir or not os.path.isdir(target_dir):
                                                                                                                                                                                                                    print(f"Error: version not found {version}", file=sys.stderr)
                                                                                                                                                                                                                            list_versions(base_dir, slug)
                                                                                                                                                                                                                                    sys.exit(1)
                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                            # First back up current version
                                                                                                                                                                                                                                                backup(base_dir, slug)
                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                        # Restore files
                                                                                                                                                                                                                                                            for fname in ['memory.md', 'persona.md', 'SKILL.md', 'meta.json']:
                                                                                                                                                                                                                                                                    src = os.path.join(target_dir, fname)
                                                                                                                                                                                                                                                                            dst = os.path.join(skill_dir, fname)
                                                                                                                                                                                                                                                                                    if os.path.exists(src):
                                                                                                                                                                                                                                                                                                shutil.copy2(src, dst)
                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                        print(f"Rolled back to version {version}")


                                                                                                                                                                                                                                                                                                        def list_versions(base_dir: str, slug: str):
                                                                                                                                                                                                                                                                                                            """List all versions"""
                                                                                                                                                                                                                                                                                                                versions_dir = os.path.join(base_dir, slug, 'versions')
                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                        if not os.path.isdir(versions_dir):
                                                                                                                                                                                                                                                                                                                                print("No historical versions.")
                                                                                                                                                                                                                                                                                                                                        return
                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                versions = sorted(os.listdir(versions_dir), reverse=True)
                                                                                                                                                                                                                                                                                                                                                    if not versions:
                                                                                                                                                                                                                                                                                                                                                            print("No historical versions.")
                                                                                                                                                                                                                                                                                                                                                                    return
                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                            print(f"Historical versions ({len(versions)} total):\n")
                                                                                                                                                                                                                                                                                                                                                                                for v in versions:
                                                                                                                                                                                                                                                                                                                                                                                        print(f"  {v}")


                                                                                                                                                                                                                                                                                                                                                                                        def main():
                                                                                                                                                                                                                                                                                                                                                                                            parser = argparse.ArgumentParser(description='Version manager')
                                                                                                                                                                                                                                                                                                                                                                                                parser.add_argument('--action', required=True, choices=['backup', 'rollback', 'list'])
                                                                                                                                                                                                                                                                                                                                                                                                    parser.add_argument('--slug', required=True, help='Ex codename/identifier')
                                                                                                                                                                                                                                                                                                                                                                                                        parser.add_argument('--base-dir', default='./exes', help='Base directory')
                                                                                                                                                                                                                                                                                                                                                                                                            parser.add_argument('--version', help='Target version for rollback')
                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                    args = parser.parse_args()
                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                            if args.action == 'backup':
                                                                                                                                                                                                                                                                                                                                                                                                                                    backup(args.base_dir, args.slug)
                                                                                                                                                                                                                                                                                                                                                                                                                                        elif args.action == 'rollback':
                                                                                                                                                                                                                                                                                                                                                                                                                                                if not args.version:
                                                                                                                                                                                                                                                                                                                                                                                                                                                            print("Error: rollback requires --version argument", file=sys.stderr)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        sys.exit(1)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                rollback(args.base_dir, args.slug, args.version)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    elif args.action == 'list':
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            list_versions(args.base_dir, args.slug)


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if __name__ == '__main__':
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                main()